data/collections/IS2SITMOGR4-cog.json, data/collections/geoglam.json
Fixes NASA-IMPACT/veda-data-pipelines#221 and 
Fixes NASA-IMPACT/veda-data-pipelines#281 at the configuration level in the repo.
=> Fix collections that have intermittent data

dags/veda_data_pipeline/groups/processing_group.py
Fixing the import statement 
* Change the import statment in dags/veda_data_pipeline/groups/processing_group.py file
=> Fix import error

dags/veda_data_pipeline/groups/processing_group.py
Change the submit stac to have parameters from airflow variables
*Use airflow variables for stac submit
=> CHange the commit of the tasks

.github/workflows/cicd.yml, infrastructure/custom_policies/main.tf, infrastructure/custom_policies/variables.tf, infrastructure/main.tf, infrastructure/task_definition.tf, infrastructure/variables.tf
Various fixes for terraform, cicd, formatting.
=> Cicd, tf fixes

.pre-commit-config.yaml, docker_tasks/vector_ingest/handler.py
1. someone removed something (probably through rebase) that was already in `main`, now our pipeline is broken
2. add a pre-commit hook so we don't have grok CI feedback and it does it for us
=> adding back correct refresh url

.pre-commit-config.yaml, docker_tasks/vector_ingest/handler.py
=> move t_ed selection to main

infrastructure/rds.tf, infrastructure/variables.tf
Trying provision RDS cluster in DEV as a test case
* Add RDS cluster
=> Adding temp RDS to verify

dags/rds_example_dag.py, dags/requirements.txt
Adding an example DAG
* requirements
=> Adding requirements and RDS_DAG_example

dags/requirements-constraints.txt, dags/requirements.txt, infrastructure/rds.tf
Update the requirements for RDS cluster 
* requirements constraints
=> Update the requirements for MWAA to support RDS cluster

infrastructure/rds.tf
temporary disable the delete protection from RDS
=> temporary disable the protection

infrastructure/rds.tf
Only provision RDS cluster in dev
=> use count to only provision RDS in dev env

infrastructure/rds.tf
DEV only RDS cluster provision
=> RDS cluster provision for dev only

dags/requirements-constraints.txt, infrastructure/main.tf
Add ECS insights feature to containerized tasks
=> Add ECS insights feature to containerized tasks

dags/requirements-constraints.txt, infrastructure/main.tf, infrastructure/rds.tf
push out the newest changes
* Detailed list or prose of changes
* ...
=> push out the newest changes

infrastructure/main.tf
=> Change to public subnet

infrastructure/main.tf
Reverts NASA-IMPACT/veda-data-airflow#54
=> Revert "Change to public subnet"

.github/workflows/cicd.yml, infrastructure/main.tf
* Detailed list or prose of changes
* ...
=> revert  change to public subnet

dags/veda_data_pipeline/veda_process_vector_pipeline.py, docker_tasks/vector_ingest/Dockerfile, docker_tasks/vector_ingest/handler.py, docker_tasks/vector_ingest/requirements.txt, infrastructure/.terraform.lock.hcl
Updating the base image to accelerate vector_ingest task
* Updating dockerfile to use lambgio/gdal base image
* Update the code to capture the error in stdout and stderr
=> Accelerate vector ingest ECS task

.flake8, .pre-commit-config.yaml, docker_tasks/vector_ingest/handler.py
*   it seems `.fgb`(s) get encoded with a name when written to disk and since in the last PRs we are changing the names of the files during an `s3.copy` operation from the algorithm the original name is still needed in `-sql` statements to read the file 😞 . So fix that. 
Here's the first line of the file:
```python
ubuntu@ip-10-0-1-254:~$ cat /tmp/snapshot_fireline_nrt.fgb | head -n1 
fgbfgb  
\0lD\:4
>%w{A;܂DAy,fireline
d_$0#PROJCRS["NAD27 / US National Atlas Equal Area",BASEGEOGCRS["NAD27",DATUM["North American Datum 1927",ELLIPSOID["Clarke 1866",6378206.4,294.978698213898,LENGTHUNIT["metre",1]]],PRIMEM["Greenwich",0,ANGLEUNIT["degree",0.0174532925199433]],ID["EPSG",4267]],CONVERSION["unnamed",METHOD["Lambert Azimuthal Equal Area",ID["EPSG",9820]],PARAMETER["Latitude of natural …
```
=> ogr2ogr ingest bug on renamed files

docker_tasks/vector_ingest/handler.py
* do  a temporary column remapping of similar collections for Large Fire
* write a ticket to remove all this conditional logic during ingest and force the scientists to do it in the algorithm b/c this shouldn't have to change at all
=> FireAtlas Column Remapping

docker_tasks/vector_ingest/handler.py
=> Collection Name Bug

infrastructure/main.tf
Adding tag to all resources 
* Upgrade base TF module
=> Upgrade base module to support tags

docker_tasks/build_stac/handler.py, docker_tasks/build_stac/utils/stac.py, scripts/item.py
**Summary:** STAC creation bugfixes and fail hard when errors occur
Ingest should now fail after errors are encountered while building STAC items. A few errors that were previously missed have also been addressed.
=> Fix STAC item creation bugs; avoid swallowing errors

docker_tasks/vector_ingest/handler.py
Ogr2ogr command for FWI dataset.
=> ogr2ogr command for FWI Dataset

.github/workflows/tags.yml, workflows_api/runtime/src/main.py
- Include type in discovery endpoint
- include tagging in workflows
=> Discovery endpoint include type, workflows tagging

.github/workflows/tags.yml
Include on push main for tagging workflow
=> chore: include on push main for tagging workflow

.github/actions/terraform-deploy/action.yml, infrastructure/main.tf
* There's a discrepancy in the prefix strings that caused an issue when we were testing
=> fix: update to rely on prefix variable to name resources

dags/example_dag.py
=> test change in example dag

infrastructure/main.tf
=> Change tf main auth clients

infrastructure/main.tf, workflows_api/runtime/requirements.txt, workflows_api/runtime/src/main.py, workflows_api/runtime/src/monitoring.py
**Summary:** Addresses #114 and #124 
* Implements basic logging, tracing, metrics using same pattern as our other services
* Adds dependencies for lambda image updates in terraform
~- [ ] Unit tests~
~- [ ] Integration tests~
=> feat(otel): Add otel, update image on push

README.md
Addresses [VEDA-134: Develop amazing new feature](https://github.com/NASA-IMPACT/veda-data-pipelines/issues/134)
* Adding instructions to readme regarding the cognito callback url
=> feat: add instructions in readme regarding cognito domain callback urls

.env.example, infrastructure/main.tf, infrastructure/terraform.tfvars.tmpl, infrastructure/variables.tf
* Updated the terraform configuration to include another variable `backend_vpc_id` to use for the lambda security group.
=> fix: add backend_vpc_id variable

workflows_api/runtime/requirements.txt
* Upgrade xarray to `2024.06.0`
=> fix: upgrade xarray

dags/generate_dags.py, dags/veda_data_pipeline/groups/discover_group.py, docker_tasks/build_stac/requirements.txt
- Fix for "Dag import error" when there's no scheduled collection ingests
- Fix for s3 files not found when it's not a scheduled discovery
=> (fix): non scheduled discovery and dag import error

workflows_api/runtime/src/airflow_helpers.py, workflows_api/runtime/src/main.py, workflows_api/runtime/src/schemas.py
Addresses [169](https://github.com/NASA-IMPACT/veda-data-airflow/issues/169)
* Added response model
* Added parser
=> fix: list workflows API 

infrastructure/variables.tf
* Detailed list or prose of changes
* ...
=> fix: add missing bracket

.github/actions/terraform-deploy/action.yml
Addresses https://github.com/NASA-IMPACT/veda-data-airflow/issues/195
* Updated deploy step to output workflows_api endpoint value
=> feat: update deploy step to output workflows api endpoint

infrastructure/main.tf, infrastructure/mwaa_environment_variables.tpl
Add back read, write assume arns
was removed in PR: https://github.com/NASA-IMPACT/veda-data-airflow/pull/111/files#diff-d43416ce46ddce36acc7d966301dbbc99dd31b12064f100739f8b70e4c122a73
=> Add back read, write assume arns

docker_tasks/vector_ingest/Dockerfile, infrastructure/main.tf, infrastructure/mwaa_environment_variables.tpl
Let's try this again with the image building
=> Promote `dev` to `main`

infrastructure/main.tf
Fixes vector subnet ids reference
=> fix: vector subnet id reference

.github/actions/terraform-deploy-sm2a/action.yml, dags/generate_dags.py, sm2a/Makefile, sm2a/infrastructure/main.tf, sm2a/infrastructure/variables.tf
We are making this PR to avoid a large PR when we migrate. I am expecting having so many smaller/manageable PRs before reaching the point of MWAA to SM2A migration
=> Clean up SM2A deployment before MWAA to SM2A migration
